name: flutter_radio_player_2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  audioplayers: ^5.0.0
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  google_fonts: ^4.0.4
  path_provider: ^2.0.15
  go_router: ^10.0.0
  dismissible_page: ^1.0.2
  lottie: ^2.5.0
  intl: ^0.18.1

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1 
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter_native_splash:  
 color: '#673AB7'
 image: assets/images/splash.png
 android_12:
   image: assets/images/splash.png
 android: true,
 ios: false,
 web: false,

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
  adaptive_icon_foreground: 'assets/icon/ic_foreground.png'
  adaptive_icon_background: 'assets/icon/ic_background.png'
  macos:
    generate: true
    image_path: "assets/icon/icon.png" 


 
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/sounds/
     - assets/details_animation_music.json
  